Postgresql = "postgresql://postgres:123@postgres:5432/social?sslmode=disable"
Memcache = "memcached:11211"
Bind = ":80"
BindLTS = ":443"
Host = "vbambuke.ru"
AvatarDir = "/home/web/avatars/"
CertDir = "/home/web/certs"
